#ifndef PROJEKT_LCVRP_CONSTANTSGENETICALGORITHM_H
#define PROJEKT_LCVRP_CONSTANTSGENETICALGORITHM_H

const int DEFAULT_MIN_POPULATION_SIZE = 10;
const double DEFAULT_MUTATION_PROB = 0.02;
const double DEFAULT_CROSSING_PROB = 0.8;
const int DEFAULT_MIN_TOURNAMENT_SIZE = 2;

#endif //PROJEKT_LCVRP_CONSTANTSGENETICALGORITHM_H